name: Synchronise DNS records

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  # Synchronise once per week
  schedule:
    - cron: "0 8 * * WED"

permissions:
  contents: read

jobs:
  # Sync records using inwx-dns-recordmaster
  sync-records:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
      - name: Install inwx-dns-recordmaster
        run: pip install -r requirements.txt
      - name: Display information about inwx-dns-recordmaster
        run: inwx-dnsrm --version
      - name: Create app configuration
        run: |
          mkdir -p $HOME/.config/inwx-dns-recordmaster/
          cp config.toml $HOME/.config/inwx-dns-recordmaster/config.toml
          # Replace secrets in app config
          sed -i "s|__INWX_USER__|${{ secrets.INWX_USER }}|" $HOME/.config/inwx-dns-recordmaster/config.toml
          sed -i "s|__INWX_PASS__|${{ secrets.INWX_PASS }}|" $HOME/.config/inwx-dns-recordmaster/config.toml
      - name: Run inwx-dnsrm (dry mode in Pull Request)
        run: inwx-dnsrm sync -c records --dry
        if: github.event_name == 'pull_request'
      - name: Run inwx-dnsrm (prod mode)
        run: inwx-dnsrm sync -c records
        if: github.event_name != 'pull_request'
